### ISSUE TITLE
Problème arrondi

### ISSUE THREAD

**Issue by ilil2** [ilil2/The-Timeless-Chronicles-Eon-s-Legacy#40]
probleme d'arrondi sur la map lvl1

**Comment by Darkrentin** [comment]
Bug Patch
Changer Math.Floor par Math.Ceiling
Me demander pas pourquoi arrondire au supérieur est mieux que d'arrondire a l'inferieur

![ron-swanson-computer](https://github.com/ilil2/The-Timeless-Chronicles-Eon-s-Legacy/assets/79848980/81f55fc5-733e-4367-8756-e0fa509341ae)
